Track some dependency updates
VelocityPowered/Velocity pull request #366
Opened 2020-09-15 11:29 UTC by derklaro

junit: 5.3.0-M1 -> 5.7.0
slf4j: 1.7.25 -> 1.7.30
netty: 4.1.51.Final -> 4.1.52.Final
guava: 25.1-jre -> 29.0-jre
checkerFramework: 2.7.0 -> 3.6.1
jline-terminal-jansi: 3.12.1 -> 3.16.0
fastutil: 8.2.3 -> 8.4.1
async-http-client: 2.10.4 -> 2.12.1
completable-futures: 0.3.2 -> 0.3.3
gradle-wrapper: 6.6 -> 6.6.1

BREAKING CHANGE: No breaking change

2020-09-19 20:50 UTC, astei requested changes

2020-09-19 20:50 UTC, astei commented on build.gradle
> +        guavaVersion = '29.0-jre'
Contrary to your opinion, bumping the Guava version _is_ a breaking change.

2020-09-19 22:05 UTC, astei commented
The rest of these changes look fine for me. Remove the Guava bump and I'm more than happy to merge this in.

2020-09-19 22:09 UTC, merged

2020-09-20 08:52 UTC, derklaro commented
Thank you doing it for me. I am in germany and just woke up xD